version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=salud_user
      - POSTGRES_PASSWORD=salud_password
      - POSTGRES_DB=salud_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U salud_user -d salud_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./scripts:/app/scripts
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://salud_user:salud_password@db:5432/salud_db
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --reload"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  init-db:
    build: 
      context: ./backend
      dockerfile: Dockerfile.init
    volumes:
      - ./scripts:/app/scripts
    environment:
      - DATABASE_URL=postgresql://salud_user:salud_password@db:5432/salud_db
    depends_on:
      - backend
    command: sh -c "sleep 15 && python /app/scripts/generate_test_data.py"

volumes:
  postgres_data: